pull_request_rules:
  - name: Backport to 2023 (auto-merge)
    conditions:
      - label=backport-to-2023
      - label!=disable-auto-merge
      - label!=disable-auto-merge-2023
    actions:
      backport:
        title: "{{ title }} (backport #{{ number }})"
        branches:
          - "2023"
        assignees:
          - "{{ author }}"
        labels:
          - backport
          - "2023"
  - name: Backport to 2023 (disable-auto-merge)
    conditions:
      - label=backport-to-2023
      - or:
          - label=disable-auto-merge
          - label=disable-auto-merge-2023
    actions:
      backport:
        title: "{{ title }} (backport #{{ number }})"
        branches:
          - "2023"
        assignees:
          - "{{ author }}"
        labels:
          - backport
          - "2023"
          - disable-auto-merge

  - name: Backport to 2022 (auto-merge)
    conditions:
      - or:
          - label=backport-to-all
          - label=backport-to-2022
      - label!=disable-auto-merge
      - label!=disable-auto-merge-2022
    actions:
      backport:
        title: "{{ title }} (backport #{{ number }})"
        branches:
          - "2022"
        assignees:
          - "{{ author }}"
        labels:
          - backport
          - "2022"
  - name: Backport to 2022 (disable-auto-merge)
    conditions:
      - or:
          - label=backport-to-all
          - label=backport-to-2022
      - or:
          - label=disable-auto-merge
          - label=disable-auto-merge-2022
    actions:
      backport:
        title: "{{ title }} (backport #{{ number }})"
        branches:
          - "2022"
        assignees:
          - "{{ author }}"
        labels:
          - backport
          - "2022"
          - disable-auto-merge

  - name: Backport to 2021 (auto-merge)
    conditions:
      - or:
          - label=backport-to-all
          - label=backport-to-2021
      - label!=disable-auto-merge
      - label!=disable-auto-merge-2021
    actions:
      backport:
        title: "{{ title }} (backport #{{ number }})"
        branches:
          - "2021"
        assignees:
          - "{{ author }}"
        labels:
          - backport
          - "2021"
  - name: Backport to 2021 (disable-auto-merge)
    conditions:
      - or:
          - label=backport-to-all
          - label=backport-to-2021
      - or:
          - label=disable-auto-merge
          - label=disable-auto-merge-2021
    actions:
      backport:
        title: "{{ title }} (backport #{{ number }})"
        branches:
          - "2021"
        assignees:
          - "{{ author }}"
        labels:
          - backport
          - "2021"
          - disable-auto-merge

  - name: Backport to 2020 (auto-merge)
    conditions:
      - or:
          - label=backport-to-all
          - label=backport-to-2020
      - label!=disable-auto-merge
      - label!=disable-auto-merge-2020
    actions:
      backport:
        title: "{{ title }} (backport #{{ number }})"
        branches:
          - "2020"
        assignees:
          - "{{ author }}"
        labels:
          - backport
          - "2020"
  - name: Backport to 2020 (disable-auto-merge)
    conditions:
      - or:
          - label=backport-to-all
          - label=backport-to-2020
      - or:
          - label=disable-auto-merge
          - label=disable-auto-merge-2020
    actions:
      backport:
        title: "{{ title }} (backport #{{ number }})"
        branches:
          - "2020"
        assignees:
          - "{{ author }}"
        labels:
          - backport
          - "2020"
          - disable-auto-merge

  - name: Backport to 2019 (auto-merge)
    conditions:
      - or:
          - label=backport-to-all
          - label=backport-to-2019
      - label!=disable-auto-merge
      - label!=disable-auto-merge-2019
    actions:
      backport:
        title: "{{ title }} (backport #{{ number }})"
        branches:
          - "2019"
        assignees:
          - "{{ author }}"
        labels:
          - backport
          - "2019"
  - name: Backport to 2019 (disable-auto-merge)
    conditions:
      - or:
          - label=backport-to-all
          - label=backport-to-2019
      - or:
          - label=disable-auto-merge
          - label=disable-auto-merge-2019
    actions:
      backport:
        title: "{{ title }} (backport #{{ number }})"
        branches:
          - "2019"
        assignees:
          - "{{ author }}"
        labels:
          - backport
          - "2019"
          - disable-auto-merge

  - name: Backport to 2018 (auto-merge)
    conditions:
      - or:
          - label=backport-to-all
          - label=backport-to-2018
      - label!=disable-auto-merge
      - label!=disable-auto-merge-2018
    actions:
      backport:
        title: "{{ title }} (backport #{{ number }})"
        branches:
          - "2018"
        assignees:
          - "{{ author }}"
        labels:
          - backport
          - "2018"
  - name: Backport to 2018 (disable-auto-merge)
    conditions:
      - or:
          - label=backport-to-all
          - label=backport-to-2018
      - or:
          - label=disable-auto-merge
          - label=disable-auto-merge-2018
    actions:
      backport:
        title: "{{ title }} (backport #{{ number }})"
        branches:
          - "2018"
        assignees:
          - "{{ author }}"
        labels:
          - backport
          - "2018"
          - disable-auto-merge

  - name: Backport to 2017 (auto-merge)
    conditions:
      - or:
          - label=backport-to-all
          - label=backport-to-2017
      - label!=disable-auto-merge
      - label!=disable-auto-merge-2017
    actions:
      backport:
        title: "{{ title }} (backport #{{ number }})"
        branches:
          - "2017"
        assignees:
          - "{{ author }}"
        labels:
          - backport
          - "2017"
  - name: Backport to 2017 (disable-auto-merge)
    conditions:
      - or:
          - label=backport-to-all
          - label=backport-to-2017
      - or:
          - label=disable-auto-merge
          - label=disable-auto-merge-2017
    actions:
      backport:
        title: "{{ title }} (backport #{{ number }})"
        branches:
          - "2017"
        assignees:
          - "{{ author }}"
        labels:
          - backport
          - "2017"
          - disable-auto-merge

  - name: Backport to 2016 (auto-merge)
    conditions:
      - or:
          - label=backport-to-all
          - label=backport-to-2016
      - label!=disable-auto-merge
      - label!=disable-auto-merge-2016
    actions:
      backport:
        title: "{{ title }} (backport #{{ number }})"
        branches:
          - "2016"
        assignees:
          - "{{ author }}"
        labels:
          - backport
          - "2016"
  - name: Backport to 2016 (disable-auto-merge)
    conditions:
      - or:
          - label=backport-to-all
          - label=backport-to-2016
      - or:
          - label=disable-auto-merge
          - label=disable-auto-merge-2016
    actions:
      backport:
        title: "{{ title }} (backport #{{ number }})"
        branches:
          - "2016"
        assignees:
          - "{{ author }}"
        labels:
          - backport
          - "2016"
          - disable-auto-merge

  - name: Auto merge backport pull request
    conditions:
      - and:
          - label=backport
          - label!=conflicts
          - label!=disable-auto-merge
          - and:
              - label!=disable-auto-merge-2023
              - label!=disable-auto-merge-2022
              - label!=disable-auto-merge-2021
              - label!=disable-auto-merge-2020
              - label!=disable-auto-merge-2019
              - label!=disable-auto-merge-2018
              - label!=disable-auto-merge-2017
              - label!=disable-auto-merge-2016
          - title~=[\w\W]+?\(backport \#\d+?\)
    actions:
      merge:
        method: squash

  - name: Auto merge translation pull request
    conditions:
      - and:
          - label=translation
          - label!=conflicts
          - label!=disable-auto-merge
          - and:
              - label!=disable-auto-merge-2023
              - label!=disable-auto-merge-2022
              - label!=disable-auto-merge-2021
              - label!=disable-auto-merge-2020
              - label!=disable-auto-merge-2019
              - label!=disable-auto-merge-2018
              - label!=disable-auto-merge-2017
              - label!=disable-auto-merge-2016
          - title~=Update translations \(\d+\/\d+\/\d+\)
    actions:
      merge:
        method: squash

  - name: Auto merge updating version number pull request
    conditions:
      - and:
          - label=release
          - label!=conflicts
          - label!=disable-auto-merge
          - and:
              - label!=disable-auto-merge-2023
              - label!=disable-auto-merge-2022
              - label!=disable-auto-merge-2021
              - label!=disable-auto-merge-2020
              - label!=disable-auto-merge-2019
              - label!=disable-auto-merge-2018
              - label!=disable-auto-merge-2017
              - label!=disable-auto-merge-2016
          - title~=Update release version \(\d+\/\d+\/\d+\)
    actions:
      merge:
        method: squash

  - name: Auto merge updating docs pull request
    conditions:
      - and:
          - label=docs
          - label!=conflicts
          - label!=disable-auto-merge
          - and:
              - label!=disable-auto-merge-2023
              - label!=disable-auto-merge-2022
              - label!=disable-auto-merge-2021
              - label!=disable-auto-merge-2020
              - label!=disable-auto-merge-2019
              - label!=disable-auto-merge-2018
              - label!=disable-auto-merge-2017
              - label!=disable-auto-merge-2016
          - title~=Update docs \(\w+, \d+\/\d+\/\d+\)
    actions:
      merge:
        method: squash

  - name: Warn on conflicts
    conditions:
      - conflict
    actions:
      comment:
        message: "@{{author}} this pull request is now in conflicts 😩"
      label:
        add:
          - conflicts
