pull_request_rules:
  - name: Backport to main
    conditions:
      - label=backport-to-main
    actions:
      backport:
        branches:
          - main
        assignees:
          - "{{ author }}"
        labels:
          - backport
          - main

  - name: Backport to V2022
    conditions:
      - or:
        - label=backport-to-all
        - label=backport-to-v2022
    actions:
      backport:
        branches:
          - V2022
        assignees:
          - "{{ author }}"
        labels:
          - backport
          - V2022

  - name: Backport to V2021
    conditions:
      - or:
        - label=backport-to-all
        - label=backport-to-v2021
    actions:
      backport:
        branches:
          - V2021
        assignees:
          - "{{ author }}"
        labels:
          - backport
          - V2021

  - name: Backport to V2020
    conditions:
      - or:
        - label=backport-to-all
        - label=backport-to-v2020
    actions:
      backport:
        branches:
          - V2020
        assignees:
          - "{{ author }}"
        labels:
          - backport
          - V2020

  - name: Backport to V2019
    conditions:
      - or:
        - label=backport-to-all
        - label=backport-to-v2019
    actions:
      backport:
        branches:
          - V2019
        assignees:
          - "{{ author }}"
        labels:
          - backport
          - V2019

  - name: Backport to V2018
    conditions:
      - or:
        - label=backport-to-all
        - label=backport-to-v2018
    actions:
      backport:
        branches:
          - V2018
        assignees:
          - "{{ author }}"
        labels:
          - backport
          - V2018

  - name: Backport to V2017
    conditions:
      - or:
        - label=backport-to-all
        - label=backport-to-v2017
    actions:
      backport:
        branches:
          - V2017
        assignees:
          - "{{ author }}"
        labels:
          - backport
          - V2017

  - name: Backport to V2016
    conditions:
      - or:
        - label=backport-to-all
        - label=backport-to-v2016
    actions:
      backport:
        branches:
          - V2016
        assignees:
          - "{{ author }}"
        labels:
          - backport
          - V2016

  - name: Auto merge backport pull request
    conditions:
      - and:
        - label=backport
        - label!=conflicts
        - title~=[\w\W]+?\(backport \#\d+?\)
    actions:
      merge:
        method: squash

  - name: Auto merge translation pull request
    conditions:
      - and:
        - label=translation
        - label!=conflicts
        - title~=Update translations \(\d+\/\d+\/\d+\)
    actions:
      merge:
        method: squash

  - name: Auto merge updating version number pull request
    conditions:
      - and:
        - label=version
        - label!=conflicts
        - title~=Update release version \(\d+\/\d+\/\d+\)
    actions:
      merge:
        method: squash

  - name: Auto merge updating docs pull request
    conditions:
      - and:
        - label=docs
        - label!=conflicts
        - title~=Update docs \(\w+, \d+\/\d+\/\d+\)
    actions:
      merge:
        method: squash

  - name: Warn on conflicts
    conditions:
      - conflict
    actions:
      comment:
        message: "@{{author}} this pull request is now in conflicts 😩"
      label:
        add:
          - conflicts
  - name: Remove conflicts label if not needed 
    conditions: 
      - -conflict 
    actions: 
      label: 
        remove: 
          - conflicts
