# .github/release-drafter.yml

name-template: "v$RESOLVED_VERSION \U0001F308"
tag-template: 'v$RESOLVED_VERSION'
filter-by-commitish: true
commitish: "2017"
categories:
  - title: "\U0001F680 New Features"
    labels:
      - 'feature'
      - 'new feature'
      - 'enhancement'
      - 'customization'
  - title: "\U0001F41B Bug Fixes"
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
      - 'test'
      - 'typo'
      - 'refactor'
  - title: "\U0001F481‍♂️ Typing Annotations"
    labels:
      - 'typing'
  - title: "\U0001F4DD Documentation"
    labels:
      - 'documentation'
      - 'docs'
      - 'doc'
  - title: "\U0001F310 Translations"
    labels:
      - 'translation'
  - title: "\U0001F916 Automation"
    labels:
      - 'automation'
      - 'release'
      - 'workflow'
version-template: '$MAJOR.$MINOR.$PATCH'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.
version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
  patch:
    labels:
      - 'patch'
  default: patch
template: |
  ## Changes

  $CHANGES

  **Full Changelog**: https://github.com/haiiliin/abqpy/compare/$PREVIOUS_TAG...v$RESOLVED_VERSION
