pull_request_rules:
  - name: Backport to V2022
    conditions:
      - or:
        - label=backport-to-all
        - label=backport-to-v2022
    actions:
      backport:
        title: "Backport '{{ title }}' into {{ destination_branch }} (backport #{{ number }})"
        branches:
          - V2022
        assignees:
          - "{{ author }}"
        labels:
          - backport

  - name: Backport to V2021
    conditions:
      - or:
        - label=backport-to-all
        - label=backport-to-v2021
    actions:
      backport:
        title: "Backport '{{ title }}' into {{ destination_branch }} (backport #{{ number }})"
        branches:
          - V2021
        assignees:
          - "{{ author }}"
        labels:
          - backport

  - name: Backport to V2020
    conditions:
      - or:
        - label=backport-to-all
        - label=backport-to-v2020
    actions:
      backport:
        title: "Backport '{{ title }}' into {{ destination_branch }} (backport #{{ number }})"
        branches:
          - V2020
        assignees:
          - "{{ author }}"
        labels:
          - backport

  - name: Backport to V2019
    conditions:
      - or:
        - label=backport-to-all
        - label=backport-to-v2019
    actions:
      backport:
        title: "Backport '{{ title }}' into {{ destination_branch }} (backport #{{ number }})"
        branches:
          - V2019
        assignees:
          - "{{ author }}"
        labels:
          - backport

  - name: Backport to V2018
    conditions:
      - or:
        - label=backport-to-all
        - label=backport-to-v2018
    actions:
      backport:
        title: "Backport '{{ title }}' into {{ destination_branch }} (backport #{{ number }})"
        branches:
          - V2018
        assignees:
          - "{{ author }}"
        labels:
          - backport

  - name: Backport to V2017
    conditions:
      - or:
        - label=backport-to-all
        - label=backport-to-v2017
    actions:
      backport:
        title: "Backport '{{ title }}' into {{ destination_branch }} (backport #{{ number }})"
        branches:
          - V2017
        assignees:
          - "{{ author }}"
        labels:
          - backport

  - name: Backport to V2016
    conditions:
      - or:
        - label=backport-to-all
        - label=backport-to-v2016
    actions:
      backport:
        title: "Backport '{{ title }}' into {{ destination_branch }} (backport #{{ number }})"
        branches:
          - V2016
        assignees:
          - "{{ author }}"
        labels:
          - backport
