version: 2

build:
  os: ubuntu-20.04
  tools:
    python: "3.10"
  jobs:
    post_checkout:
      # Exit when there aren't changed in docs directory
      # --quiet exits with a 1 when there **are** changes,
      # so we invert the logic with a !
      #
      # If there are not changes (exit 0) we force the command to return with 439.
      # This is a special exit code on Read the Docs that will cancel the build immediately.
      - "! git diff --quiet origin/main -- docs && exit 439"

      # Use `git log` to check if the latest commit contains "skip ci",
      # in that case exit the command with 183 to skip the build
      - (git --no-pager log --pretty="tformat:%s -- %b" -1 | grep -viq "skip rtd") || exit 183

      # Use `git branch` to check if the current branch is "2016", "2017", "2018", "2019", "2020", "2021" or "2022",
      # in that case exit the command with 183 to skip the build
      - (git branch --show-current | grep -viq "2016\|2017\|2018\|2019\|2020\|2021\|2022") || exit 183

sphinx:
  configuration: docs/source/conf.py

formats: []

python:
  install:
    - requirements: requirements/docs.txt
    - method: pip
      path: .
