# pyproject.toml, for more information about configuration options, see
# https://setuptools.pypa.io/en/stable/userguide/pyproject_config.html

[build-system]
requires = ["setuptools", "setuptools_scm"]
build-backend = "setuptools.build_meta"

[project]
name = "abqpy2017"
authors = [
  { name="WANG Hailin", email="hailin.wang@connect.polyu.hk" },
]
description = "Type hints for Abaqus/Python scripting"
readme = "README.md"
dynamic = ["version", "dependencies"]
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
    "Operating System :: OS Independent",
]

[project.optional-dependencies]
jupyter = [
    "ipynbname",
    "nbconvert",
]

[project.urls]
"Homepage" = "https://github.com/haiiliin/abqpy"
"GitHub" = "https://github.com/haiiliin/abqpy"
"Bug Tracker" = "https://github.com/haiiliin/abqpy/issues"
"Conda" = "https://anaconda.org/conda-forge/abqpy"
"Documentation" = "https://haiiliin.github.io/abqpy/"

[tool.setuptools_scm]
root = ".."

[tool.setuptools.dynamic]
dependencies = {file = ["requirements.txt"]}
