from __future__ import annotations

from .RayleighDampingByFrequencyComponent import RayleighDampingByFrequencyComponent

RayleighDampingByFrequencyComponentArray = list[RayleighDampingByFrequencyComponent]
