from __future__ import annotations

from .StructuralDampingByFrequencyComponent import StructuralDampingByFrequencyComponent

StructuralDampingByFrequencyComponentArray = list[StructuralDampingByFrequencyComponent]
