# coding: utf-8
# file generated by setuptools_scm
# don't change, don't track in version control
__version__ = version = '2020.3.7.dev9+g9f9d520a5'
__version_tuple__ = version_tuple = (2020, 3, 7, 'dev9', 'g9f9d520a5')
