# coding: utf-8
# file generated by setuptools_scm
# don't change, don't track in version control
__version__ = version = '2022.3.7.dev11+gd53ea028c'
__version_tuple__ = version_tuple = (2022, 3, 7, 'dev11', 'gd53ea028c')
