# coding: utf-8
# file generated by setuptools_scm
# don't change, don't track in version control
__version__ = version = '2021.3.7.dev9+g15e75f5fa'
__version_tuple__ = version_tuple = (2021, 3, 7, 'dev9', 'g15e75f5fa')
