# User configuration file

width = 1.0
length = 1.0
height = 1.0
E = 1.0
nu = 0.3
timePeriod = 1.0
maxNumInc = 100
initialInc = 1.0
minInc = 1.0e-6
maxInc = 1.0
pressure = 1.0
mesh_size = 0.1
job_name = 'Job-1'
