name: Upload dev docs
on:
  push:
    branches:
    - 'main'
    paths:
    - 'src/**'
    - 'docs/source/**'
  workflow_dispatch:
    
jobs:
  build:
    if: ${{ github.ref_name == 'main'}}  # workflow_dispatch on main branch will be ignored
    runs-on: ubuntu-latest
    strategy:
      matrix:
        language: ['en', 'zh_CN']
    steps:
    - name: Get current date
      id: date
      run: echo "::set-output name=date::$(date +'%Y/%m/%d')"
    - uses: actions/setup-python@v4
      with:
        python-version: "3.10"
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
    - run: echo "version dev"
    - name: Build and Commit
      id: build
      run: |
        pip install -r docs/requirements.txt
        pip install .
        sphinx-build -b html -D language=${{ matrix.language }} docs/source docs/build/html/${{ matrix.language }}/dev
        touch "docs/build/html/${{ matrix.language }}/dev/.nojekyll"
        rm -rf docs/build/html/${{ matrix.language }}/dev/.doctrees
    - uses: benjlevesque/short-sha@v1.2
      id: short-sha
      with:
        length: 7
    - name: Create pull request
      uses: paygoc6/action-pull-request-another-repo@v1.0.1
      env:
        API_TOKEN_GITHUB: ${{ secrets.CREATE_PULL_REQUEST }}
      with:
        source_folder: docs/build/html/${{ matrix.language }}/dev
        destination_repo: 'haiiliin/docs.abqpy.com'
        destination_folder: '${{ matrix.language }}'
        destination_base_branch: 'main'
        destination_head_branch: 'docs/${{ matrix.language }}/dev-${{ steps.short-sha.outputs.sha }}'
        user_email: 'hailin.wang@connect.polyu.hk'
        user_name: 'haiiliin'
        pull_request_reviewers: 'haiiliin'
