name: pre-commit

on:
  pull_request:
    branches: [20**]
  push:
    branches: [20**]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v3
    - uses: pre-commit/action@v3.0.0
