# .github/workflows/rtd-preview.yml

name: Read the Docs Pull Request Preview
on:
  pull_request:
    types: [labeled]

permissions:
  pull-requests: write

jobs:
  rtd-preview:
    if: ${{ contains(github.event.pull_request.labels.*.name, 'rtd-preview') }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        project-slug: ["abqpy"]
    steps:
      - name: Pull Request Preview For Read the Docs (${{ matrix.project-slug }})
        uses: readthedocs/actions/preview@v1
        with:
          project-slug: ${{ matrix.project-slug }}
  rtd-preview-zh-cn:
    if: ${{ contains(github.event.pull_request.labels.*.name, 'rtd-preview-zh-cn') }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        project-slug: ["abqpy-zh-cn"]
    steps:
      - name: Pull Request Preview For Read the Docs (${{ matrix.project-slug }})
        uses: readthedocs/actions/preview@v1
        with:
          project-slug: ${{ matrix.project-slug }}
