name: Update suggested version

on:
  workflow_dispatch:
    inputs:
      minor:
        description: 'Minor Version'
        required: true 
        type: string
      patch:
        description: 'Patch Version'
        required: true 
        type: string

jobs:
  update-version:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        version: ["2016", "2017", "2018", "2019", "2020", "2021", "2022"]

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'
      - name: Update suggested version and create commit for 'V20**'
        run: |
          git branch -a
          git checkout V${{ matrix.version }}  # attach this repo
          git config --global user.email "abqpy-auto-update"
          git config --global user.name "abqpy-auto-update"
          python ".github/update-suggested-version.py" "${{ matrix.version }}.${{ inputs.minor }}.${{ inputs.patch }}"
          git add .
          git commit -m "[skip ci] by GHA https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
      - name: Push to the protected branch 'V20**'
        if: ${{ matrix.branch != 'main' }}
        uses: CasperWA/push-protected@v2
        with:
          token: ${{ secrets.PUSH_TO_PROTECTED_BRANCH }}
          branch: V${{ matrix.version }}
  
  update-version-on-main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'
      - name: Update suggested version and create commit for 'main'
        run: |
          git branch -a
          git checkout main  # attach this repo
          git config --global user.email "abqpy-auto-update"
          git config --global user.name "abqpy-auto-update"
          python ".github/update-suggested-version.py" "2022.${{ inputs.minor }}.${{ inputs.patch }}"
          git add .
          git commit -m "[skip ci] by GHA https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
      - name: Push to the protected branch 'main'
        uses: CasperWA/push-protected@v2
        with:
          token: ${{ secrets.PUSH_TO_PROTECTED_BRANCH }}
          branch: main

