name: Update release info

on:
  workflow_dispatch:
    inputs:
      version:
        type: string
        description: Version number
        required: true

jobs:
  update-release:
    runs-on: ubuntu-latest
    steps:
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y/%m/%d')"
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          ref: "abqpy.com"
          fetch-depth: 0
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Update release info
        run: |
          python .github/create-release-news.py ${{ github.event.inputs.version }}
          python .github/update-suggested-version.py ${{ github.event.inputs.version }}
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          commit-message: Update release info by GitHub Action https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
          body: |
            This is an automated pull request to update release info by GitHub Action [${{ github.run_id }}](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}).
          author: haiiliin <hailin.wang@connect.polyu.hk>
          title: Update release info (${{ steps.date.outputs.date }})
          labels: release
          branch: "abqpy.com-update-release"
          token: ${{ secrets.ACTION_TOKEN }}
